//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtualdlandy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoItem
    {
        public int Id { get; set; }
        public int cantidad { get; set; }
        public decimal total { get; set; }
        public int Pedido_Id { get; set; }
        public int Producto_Id { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
