//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtualdlandy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    
    public partial class Producto
    {
        public int Id { get; set; }
        public string descripcion { get; set; }
        public int stock { get; set; }
        public decimal precio { get; set; }
        [DisplayName("Upload File")]
        public string imagen { get; set; }
        public int Categoria_Id { get; set; }    
        public virtual Categoria Categoria { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

    }
}
